### ISSUE TITLE
Concept question

### ISSUE THREAD

**Issue by testman42** [tjoen/fallback-sarcasm#1]
>It repeats the utterance with a high pitched en-GB voice through picotts

how is that sarcasm? 🤔

**Comment by tjoen** [comment]
Well, it does an excellent impression of the english queen right now.

I just added a r2d2 voice. And I added a dialogfile with funny responces.

Point being, the mimic voice does not have pitch control and ssml. So there is no way to get an funny voice, or intonation.   Programming real sarcasm is pretty hard, if you are using a device without learning capabilities or context. Because it's a fallback skill, it does not understand what it text it gets.

I needed something else then the default, "I'm sorry , i did not ......" dialog

Maybe the name is a bit confusing.
